# k8s/30-service-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: nginx-demo
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80